// projects/application/frontend/app/src/app/features/navigation/components/left-navigation-sidebar/left-navigation-sidebar.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

import { navigationConfig } from '@features/navigation-config';

import { NavigationTreeComponent } from '../navigation-tree/navigation-tree.component';

@Component({
  selector: 'app-left-navigation-sidebar',
  imports: [NavigationTreeComponent],
  template: `
    <nav class="sidebar">
      <app-navigation-tree [items]="navItems" />
    </nav>
  `,
  styles: [`
    .sidebar {
      width: 280px;
      height: 100%;
      overflow-y: auto;
      border-right: 1px solid var(--app-divider);
      background-color: var(--app-bg-paper);
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
/** Permanent left sidebar (280px) rendering the app navigation tree. */
export class LeftNavigationSidebarComponent {
  readonly navItems = navigationConfig.items;
}

// projects/application/frontend/app/src/features/navigation/LeftNavigationSidebar.tsx
import { Drawer, Box } from '@mui/material';
import { NavigationTree } from './NavigationTree';
import { navigationConfig } from '@/features/navigation-config';
import { SIDEBAR_WIDTHS, HEADER_HEIGHT } from '@/features/layouts';

/**
 * LeftNavigationSidebar
 *
 * Persistent navigation sidebar for desktop viewports.
 * Displays below the header and contains the hierarchical navigation tree.
 */
export function LeftNavigationSidebar() {
  return (
    <Drawer
      variant="permanent"
      sx={{
        width: SIDEBAR_WIDTHS.left,
        flexShrink: 0,
        '& .MuiDrawer-paper': {
          width: SIDEBAR_WIDTHS.left,
          boxSizing: 'border-box',
          top: HEADER_HEIGHT,
          height: `calc(100vh - ${HEADER_HEIGHT}px)`,
          borderRight: 1,
          borderColor: 'divider',
          bgcolor: 'background.paper',
        },
      }}
    >
      <Box
        sx={{
          overflow: 'auto',
          p: 2,
          height: '100%',
        }}
      >
        <NavigationTree items={navigationConfig.items} />
      </Box>
    </Drawer>
  );
}
